### Application configuration.

# port to serve the API
server:
  port: 8091

# path to legacy data file (inside resources)
json:
  legacyDataFilePath: lançamento-conta-legado.json

# jmx
spring.jmx:
   enabled: false

#
spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

# enabled only for production
security:
  basic:
    enabled: false
